name: CodeQL Analysis

on:
  push:
    branches:
      - main  # Set to your default branch (e.g., 'main' or 'master')
  pull_request:
    branches:
      - main  # Also run on PRs to the default branch

jobs:
  analyze:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CodeQL
      uses: github/codeql-action/init@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
