name: CodeQL Analysis

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Set the Java version for your project, e.g., '8', '11', '16'
          distribution: 'temurin'

      - name: Set up CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build project
        run: |
          cd back/recipe
          ./mvnw clean install  # Or appropriate build command for your Java project

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: java
          
          
