name: CodeQL Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Set the Java version for your project, e.g., '8', '11', '16'
          distribution: 'corretto'

      - name: Set up CodeQL
        uses: github/codeql-action/init@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
